### ISSUE TITLE
I had e error

### ISSUE THREAD

**Issue by juverpp** [Cocotteseb/Krypton-OutlookGrid#1]
Help,  I had a error in

this.CellOver = new Point(-2, -2);

ln 401 OutlookGrid.cs

My Project has Krypton ToolKit 4.4.0.0, and compile not Krypton ToolKit 4.4.0.1

Thanks,

**Comment by Cocotteseb** [comment]
Hi juverpp,

Yes the Krypton OutlookGrid needs a slightly modified Krypton Toolkit. Depending the version you mention, you are not using my fork of Krypton Toolkit (4.4.1.0) . Please use it from here [https://github.com/Cocotteseb/Krypton/tree/master/Source/Krypton%20Components](url)

You will indeed find the CellOver property in the KryptonDataGridView.cs (https://github.com/Cocotteseb/Krypton/blob/master/Source/Krypton%20Components/ComponentFactory.Krypton.Toolkit/Controls%20Toolkit/KryptonDataGridView.cs)
