### ISSUE TITLE
Binding support?

### ISSUE THREAD

**Issue by desarrollo03TR** [Cocotteseb/Krypton-OutlookGrid#2]
What type of data can I use?

**Comment by Cocotteseb** [comment]
Hi desarrollo03TR, there is no binding support.
You need to fill the the grid in unbound mode. You have an example in the solution project Sandbox and in the documentation here : http://www.jdhsoftware.com/products/krypton-outlookgrid/documentation/
Hope this helps !

**Comment by desarrollo03TR** [comment]
Thanks!
