### ISSUE TITLE
If first column is TextAndImageColumn, grouping send error

### ISSUE THREAD

**Issue by desarrollo03TR** [Cocotteseb/Krypton-OutlookGrid#3]
Testing the control I noted that if the first column is KryptonDataGridViewTextAndImageColumn (using new TextAndImage(text, image) for filling data ), the group function (using the right click menu) send an error.

I changed the first column to KryptonDataGridViewTextBoxColumn, and the TextAndImageColumn to the second column and it is working fine.

**Comment by Cocotteseb** [comment]
Hi desarrollo03TR,

Hum there shouldn't be an error. Do you have a sample project, so that I can take a look at ?

**Comment by desarrollo03TR** [comment]
I'll recreate the project and try again.

Thanks!

**Comment by Cocotteseb** [comment]
Please reopen if you encounter the issue
