### ISSUE TITLE
problem after rebuilding solution

### ISSUE THREAD

**Issue by manhag** [Cocotteseb/Krypton-OutlookGrid#5]
at first run....it works perfect
after rebuild it show  that error
i have visual studio 2017

> System.NotSupportedException occurred
>   HResult=0x80131515
>   Message=ReadOnly controls collection
>   Source=ComponentFactory.Krypton.Toolkit
>   StackTrace:
>    at ComponentFactory.Krypton.Toolkit.KryptonReadOnlyControls.Add(Control value)
>    at KryptonOutlookGrid.SandBox.MainForm.InitializeComponent() in E:\Salem Projects\.net Projects\Krypton-OutlookGrid-master\Krypton-OutlookGrid-master\Source\KryptonOutlookGrid.SandBox\MainForm.Designer.cs:line 62
>    at KryptonOutlookGrid.SandBox.MainForm..ctor() in E:\Salem Projects\.net Projects\Krypton-OutlookGrid-master\Krypton-OutlookGrid-master\Source\KryptonOutlookGrid.SandBox\MainForm.cs:line 17
>    at KryptonOutlookGrid.SandBox.Program.Main() in E:\Salem Projects\.net Projects\Krypton-OutlookGrid-master\Krypton-OutlookGrid-master\Source\KryptonOutlookGrid.SandBox\Program.cs:line 18
> 

![image](https://user-images.githubusercontent.com/5571625/34195190-0d8de5aa-e565-11e7-96e0-9ffcc053e11c.png)

**Comment by Cocotteseb** [comment]
When you get this kind of error, there may be a problem with design dlls. Please register the Krypton*.design.dll to gac using Gacutil (with administration right) ==> preferred method.
If you cannot please reference the design dll to your project.
